# my IB Portfolio Manager docker stack
version: '3.7'

services:
  php-fpm:
    image: bitnami/php-fpm:7.4
    volumes:
      - app:/app:rw
      - db:/db:rw
    configs:
#      - source: sonata_php.ini
#        target: /opt/bitnami/php-fpm/conf/php.ini
      - source: sonata_fpm.conf
        target: /opt/bitnami/php/etc/php-fpm.conf
    networks:
      - default
      - system_dmz_network
    deploy:
      placement:
        constraints:
          - node.platform.os == linux
          - node.role == manager
#          - node.role == worker
      replicas: 1
  ib-gateway:
    image: waytrade/ib-gateway:1012.2c
    environment:
      TWS_USERID: ${TWS_USERID}
      TWS_PASSWORD: ${TWS_PASSWORD}
      TRADING_MODE: ${TRADING_MODE:-paper}
      VNC_SERVER_PASSWORD: ${VNC_SERVER_PASSWORD:-}
    ports:
      - "127.0.0.1:4001:4001"
      - "127.0.0.1:4002:4002"
      - "127.0.0.1:5900:5900"
    deploy:
      placement:
        constraints:
          - node.platform.os == linux
          - node.role == manager
#          - node.role == worker
      replicas: 0
  python:
    image: python:alpine
    command: python3 -u /app/Program.py --host ib-gateway --port 4001 --cache
    volumes:
      - ibbot:/app:rw
      - db:/db:rw
    networks:
      - default
      - system_dmz_network
    depends_on:
      - ib-gateway
    deploy:
      placement:
        constraints:
          - node.platform.os == linux
          - node.role == manager
#          - node.role == worker
      replicas: 0
  web:
    image: caddy:2.4.6-alpine
    volumes:
      - app:/app:ro
    networks:
      - default
      - system_dmz_network
    depends_on:
      - php-fpm
    configs:
      - source: sonata_Caddyfile
        target: /etc/caddy/Caddyfile
    deploy:
      placement:
        constraints:
          - node.platform.os == linux
          - node.role == manager
#         - node.role == worker
      replicas: 1

networks:
  default:
  system_dmz_network:
    external: true

configs:
  sonata_nginx.conf:
    external: true
  sonata_php.ini:
    external: true
  sonata_fpm.conf:
    external: true
  sonata_Caddyfile:
    external: true

volumes:
  app:
  ibbot:
  db:
