# my Portfolio Manager website docker stack
version: '3.7'

services:
  php-fpm:
    image: bitnami/php-fpm:7.4
    volumes:
      - app:/app:rw
      - db:/db:rw
    configs:
#      - source: sonata_php.ini
#        target: /opt/bitnami/php-fpm/conf/php.ini
      - source: sonata_fpm.conf
        target: /opt/bitnami/php/etc/php-fpm.conf
    networks:
      - default
      - system_dmz_network
    deploy:
      placement:
        constraints:
          - node.platform.os == linux
          - node.role == manager
#          - node.role == worker
      replicas: 1
  python:
    image: python:alpine
    command: python3 /app/Program.py --host 91.170.7.203
    volumes:
      - ibbot:/app:rw
      - db:/db:rw
    networks:
      - default
      - system_dmz_network
    deploy:
      placement:
        constraints:
          - node.platform.os == linux
          - node.role == manager
#          - node.role == worker
      replicas: 1
  web:
    image: caddy:2.1.1-alpine
    volumes:
      - app:/app:ro
    networks:
      - default
      - system_dmz_network
    depends_on:
      - php-fpm
    configs:
      - source: sonata_Caddyfile
        target: /etc/caddy/Caddyfile
    deploy:
      placement:
        constraints:
          - node.platform.os == linux
          - node.role == manager
#         - node.role == worker
      replicas: 1

networks:
  default:
  system_dmz_network:
    external: true

configs:
  sonata_nginx.conf:
    external: true
  sonata_php.ini:
    external: true
  sonata_fpm.conf:
    external: true
  sonata_Caddyfile:
    external: true

volumes:
  app:
  ibbot:
  db:
